#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
runApplication topoSet
runApplication createPatch -overwrite
runApplication cp 0/alpha.liquid.0 0/alpha.liquid
runApplication setFields
runApplication interBubbleEvapFoam

runApplication $(getApplication)

#------------------------------------------------------------------------------
